export enum UserTags {
  WEBMASTER = "webmaster",
  ADMIN = "admin",
  CLASS_PRESIDENT = "classpresident",
  SEC = "sec",
}

export enum LinkTypes {
  DISCORD = "discord",
  TWITTER = "twitter",
  TWITCH = "twitch",
  YOUTUBE = "youtube",
  GITHUB = "github",
  INSTAGRAM = "instagram",
  FACEBOOK = "facebook",
  LINKEDIN = "linkedin",
  EMAIL = "email",
}
export const urlRegexes = {
  [LinkTypes.DISCORD]: /^https:\/\/discord\.com\/users\/\d+$/,
  [LinkTypes.TWITTER]: /^https:\/\/twitter\.com\/[a-zA-Z0-9_]+$/,
  [LinkTypes.TWITCH]: /^https:\/\/twitch\.tv\/[a-zA-Z0-9_]+$/,
  [LinkTypes.YOUTUBE]: /^https:\/\/youtube\.com\/channel\/[a-zA-Z0-9_]+$/,
  [LinkTypes.GITHUB]: /^https:\/\/github\.com\/[a-zA-Z0-9_]+$/,
  [LinkTypes.INSTAGRAM]: /^https:\/\/instagram\.com\/[a-zA-Z0-9_]+$/,
  [LinkTypes.FACEBOOK]: /^https:\/\/facebook\.com\/[a-zA-Z0-9_]+$/,
  [LinkTypes.LINKEDIN]: /^https:\/\/linkedin\.com\/in\/[a-zA-Z0-9_]+$/,
  [LinkTypes.EMAIL]: /^mailto:[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
};
export type Link = {
  type: LinkTypes;
  url: string;
  handle: string;
};
export type User = {
  _id: string;
  username: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  pfp?: string;
  bio?: string;
  classOf?: number;
  tags?: UserTags[];
  links?: Link[];
};

export type GivenUser = {
  _id: string;
  username: string;
  firstName: string;
  lastName: string;
  email?: string;
  pfp?: string;
  bio?: string;
  classOf?: number;
  tags?: UserTags[];
  links?: Link[];
};

export type PossibleUser = PublicUser | AutoGeneratedUser;

export interface PublicUser extends UserFragment {
  username: string;
  email?: string;
  pfp?: string;
  bio?: string;
  tags?: UserTags[];
  type: 1;
  verifiedBy: string;
}

export interface AutoGeneratedUser extends UserFragment {
  type: 0;
}
export interface UserFragment {
  _id: string;
  firstName: string;
  lastName: string;
  classOf?: number;
  type: 0 | 1; // 0 = autogenerated, 1 = verified
}

export type UnverifiedUser = {
  _id: string;
  username: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
};
